### ISSUE TITLE
Deboncing suggestion

### ISSUE THREAD

**Issue by ghost** [jakubcabal/uart-for-fpga#1]
Hi!
I believe your UART's debouncer only filters 1110111 glitches but not the 0001000 types. I suggest you used the "OR"-ed version of the debouncer shift register to reset the debounced signal and an "AND"-ed version to set it.
Cheers,
Balazs,

**Comment by jakubcabal** [comment]
Hi,
you're right, of course. Better debouncer I added to the dev branch.
Cheers,
Jakub,
